### PR TITLE
Enabled configuration from json file for netstandard2.0 and targeted framework net45.

### LINKED ISSUE #12: Appsettings files can't be used to configure datadog sink
Hello,

I would like to use appsettings file to configure the datadog sink for my netcore applications :

````
"Serilog": {
    "MinimumLevel": {
      "Default": "Debug"
    },
    "WriteTo": [
      {
        "Name": "DatadogLogs",
        "Args": {
          "apiKey": "<datadogApiKey>",
          "configurationSection": {
            "url": "<datadogUrl>",
            "port": <datadogPort>,
            "useSSL": <datadogUseSSL>
          }
        }
      }
    ]
  }
````
Here is my PR to fix it : https://github.com/DataDog/serilog-sinks-datadog-logs/pull/11 ; feel free to adapt/upgrade it (I didn't handle .config or .xml files for net framework).

### PR DESCRIPTION
**Pull request by tadam75**
Hello,

When I use Logmatic in netcore applications, I always use appsettings.json files to configure the various Serilog sinks. I would like to do the same with the datadog sink, but it is currently not possible (with the version 0.1.4).

I have created this PR to give the possibility to use appsettings file that contain : 

```
"Serilog": {
    "MinimumLevel": {
      "Default": "Debug"
    },
    "WriteTo": [
      {
        "Name": "DatadogLogs",
        "Args": {
          "apiKey": "<datadogApiKey>",
          "configurationSection": {
            "url": "<datadogUrl>",
            "port": <datadogPort>,
            "useSSL": <datadogUseSSL>
          }
        }
      }
    ]
  }
```

I adapted code from https://github.com/serilog/serilog-sinks-mssqlserver , but just for netstandard2.0.

I also pushed in this PR the compatibility with net45 rather than net451.

Thank you for reviewing it :)

(Edit: Fixes #12 )

### CODE REVIEW

**Comment by achntrl** [comment]
Hi @tadam75, thank you for your contribution! We will review the PR shortly and get back to you

**Comment by achntrl** [comment]
Hi @tadam75, thank you for your contribution, I also think it will be useful to add the option of using the appsettings.json to configure the sink. 

I'm not a fan of the implementation with 2 `LoggerConfigurationDatadogExtensions` that are almost the same. 

I think we can have a configuration in code that tries to read the config from the `appsettings.json`, if it's not provided we try to get the configuration from the sink configuration and if it's not provided the default to `new DatadogConfiguration()`

Something along the lines of 

```csharp
var jsonConfiguration = ApplyMicrosoftExtensionsConfiguration.ConfigureDatadogConfiguration(configuration, configurationSection);
if (jsonConfiguration == null) {
    configuration = (configuration != null) ? configuration : new DatadogConfiguration();
}
configuration = (jsonConfiguration != null) ? jsonConfiguration : configuration
return loggerConfiguration.Sink(new DatadogSink(apiKey, source, service, host, tags, configuration), logLevel);
```

Then we only have one file with the sink creation logic

Would that fit your use case ?

**Comment by tadam75** [comment]
Hi @achntrl, there are 2 classes `LoggerConfigurationDatadogExtensions `  because of the multiple frameworks that you target in your package.
In this PR, one class is netstandard2.0 specific and use Microsoft.Extensions.Options.ConfigurationExtensions (netstandard2.0) to handle the appsettings.json file with the class `IConfigurationSection `.
The other class is built when you target a framework different than netstandard2.0. You may use System.Configuration (net framework) in this class to handle web.config file, with ConfigurationManager for example. Unfortunately I didn't have the time to do it.

If you merge the classes, you will have a lot of preprocessor directive (#if NETSTANDARD2_0) in the code, which is less readable/maintainable in my opinion. But it should work the same, so I let you choose what you prefer ;)

**Comment by tadam75** [comment]
@achntrl Rebase done !

Thanks :)

**Pull request merged**
